---
applications:
  - name: devopsadmin
    path: ./devopsadmin
    buildpacks:
      - nodejs_buildpack
    services:
      - devopsadmin-logme
    memory: 64M
    disk_quota: 128M
    random-route: true
    stack: cflinuxfs3
    env:
      OPTIMIZE_MEMORY: true
      MDSP_TENANT: ((mdspTenant))
      MDSP_REGION: ((mdspRegion))
      PROMETHEUS_URL: prometheus-((mdspTenant)).apps.((mdspRegion)).mindsphere.io
      GRAFANA_URL: grafana-((mdspTenant)).apps.((mdspRegion)).mindsphere.io
      TECH_USER_CLIENT_ID: "((techUserClientId))"
      TECH_USER_CLIENT_SECRET: "((techUserClientSecret))"
      NOTIFICATION_EMAIL: "((notificationEmail))"
      NOTIFICATION_MOBILE_NUMBER: "((notificationMobileNumber))"
  - name: prometheus
    path: ./prometheus
    buildpacks:
      - go_buildpack
    services:
      - devopsadmin-logme
    memory: 128M
    disk_quota: 1G
    random-route: false
    routes:
      - route: prometheus-((mdspTenant)).apps.((mdspRegion)).mindsphere.io
    stack: cflinuxfs3
    command: prometheus --config.file=./mindsphere-conf/prometheus.yml --log.level=info --web.listen-address=:8080 --web.route-prefix=/ --web.external-url=${PROM_EXTERNAL_URL}
    env:
      GOPACKAGENAME: github.com/prometheus/prometheus
      GOVERSION: go1.10
      GO_INSTALL_PACKAGE_SPEC: github.com/prometheus/prometheus/cmd/prometheus
      PROM_EXTERNAL_URL: "((promExternalUrl))"
  - name: grafana
    path: ./grafana
    buildpacks:
      - go_buildpack
    services:
      - grafana-postgres
      - devopsadmin-logme
    memory: 96M
    disk_quota: 256M
    random-route: false
    routes:
      - route: grafana-((mdspTenant)).apps.((mdspRegion)).mindsphere.io
    stack: cflinuxfs3
    command: grafana-server -config mindsphere-conf/defaults.custom.ini
    env:
      GOPACKAGENAME: github.com/grafana/grafana
      GOVERSION: go1.10
      GO_INSTALL_PACKAGE_SPEC: github.com/grafana/grafana/pkg/cmd/grafana-server
      GRAFANA_DATABASE_URL: "((grafanaDatabaseUrl))"
      GRAFANA_SMTP_PASSWORD: "((grafanaSmtpPassword))"
